//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UruIT.GameOfDrones.Model
{

    public partial class Logging
    {
        public int LogId { get; set; }
        public string FullException { get; set; }
        public string SimpleError { get; set; }
        public string ModuleName { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
